FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY backend/ ./
RUN go mod download
RUN go build -o main cmd/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/main .
COPY --from=builder /app/.env .
COPY frontend/frontend/dist ./dist
EXPOSE 8080
CMD ["./main"]
