FROM node:20-alpine AS frontend-builder
WORKDIR /app
COPY frontend/frontend/package*.json ./
RUN npm ci
COPY frontend/frontend/ ./
RUN npm run build

FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY backend/ ./
RUN go mod download
RUN go build -o main cmd/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/main .
COPY --from=builder /app/.env .
COPY --from=frontend-builder /app/dist ./frontend/dist
EXPOSE 8080
CMD ["./main"]
